#Workflow Name
name : practice-one
on : push
jobs:
    Lint :
        runs-on : ubuntu-latest
        steps:
            - name : Git-clone
              uses : actions/checkout@v3
            - name : NodeJS
              uses : actions/setup-node@v3
              with :
                node-version : 18
            - name : Install-NPM
              run : npm ci
            - name : Lint
              run : npm lint
            - name : output
              run : echo "Lint ..."
